# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "activerecord", ">= 7.1"
  gem "minitest", "~> 5.25"
  gem "rake", "~> 13.2"
  gem "rubocop", "~> 1.68"
  gem "sqlite3", "~> 2.1"
end
